// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/donca/user-crud/internal/posts/models"
)

// MockPostRepository is an autogenerated mock type for the PostRepository type
type MockPostRepository struct {
	mock.Mock
}

type MockPostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepository) EXPECT() *MockPostRepository_Expecter {
	return &MockPostRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, authorID, content, visibility
func (_m *MockPostRepository) Create(ctx context.Context, authorID string, content string, visibility string) (*models.Post, error) {
	ret := _m.Called(ctx, authorID, content, visibility)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.Post, error)); ok {
		return rf(ctx, authorID, content, visibility)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.Post); ok {
		r0 = rf(ctx, authorID, content, visibility)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, authorID, content, visibility)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - content string
//   - visibility string
func (_e *MockPostRepository_Expecter) Create(ctx interface{}, authorID interface{}, content interface{}, visibility interface{}) *MockPostRepository_Create_Call {
	return &MockPostRepository_Create_Call{Call: _e.mock.On("Create", ctx, authorID, content, visibility)}
}

func (_c *MockPostRepository_Create_Call) Run(run func(ctx context.Context, authorID string, content string, visibility string)) *MockPostRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPostRepository_Create_Call) Return(_a0 *models.Post, _a1 error) *MockPostRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.Post, error)) *MockPostRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, authorID
func (_m *MockPostRepository) Delete(ctx context.Context, id string, authorID string) error {
	ret := _m.Called(ctx, id, authorID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, authorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPostRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - authorID string
func (_e *MockPostRepository_Expecter) Delete(ctx interface{}, id interface{}, authorID interface{}) *MockPostRepository_Delete_Call {
	return &MockPostRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, authorID)}
}

func (_c *MockPostRepository_Delete_Call) Run(run func(ctx context.Context, id string, authorID string)) *MockPostRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPostRepository_Delete_Call) Return(_a0 error) *MockPostRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPostRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPostRepository) FindByID(ctx context.Context, id string) (*models.Post, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Post, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Post); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPostRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPostRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockPostRepository_FindByID_Call {
	return &MockPostRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPostRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockPostRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPostRepository_FindByID_Call) Return(_a0 *models.Post, _a1 error) *MockPostRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*models.Post, error)) *MockPostRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByAuthor provides a mock function with given fields: ctx, authorID, viewerID, limit, offset
func (_m *MockPostRepository) ListByAuthor(ctx context.Context, authorID string, viewerID string, limit int, offset int) ([]models.Post, error) {
	ret := _m.Called(ctx, authorID, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByAuthor")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]models.Post, error)); ok {
		return rf(ctx, authorID, viewerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []models.Post); ok {
		r0 = rf(ctx, authorID, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, authorID, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepository_ListByAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByAuthor'
type MockPostRepository_ListByAuthor_Call struct {
	*mock.Call
}

// ListByAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - viewerID string
//   - limit int
//   - offset int
func (_e *MockPostRepository_Expecter) ListByAuthor(ctx interface{}, authorID interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockPostRepository_ListByAuthor_Call {
	return &MockPostRepository_ListByAuthor_Call{Call: _e.mock.On("ListByAuthor", ctx, authorID, viewerID, limit, offset)}
}

func (_c *MockPostRepository_ListByAuthor_Call) Run(run func(ctx context.Context, authorID string, viewerID string, limit int, offset int)) *MockPostRepository_ListByAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockPostRepository_ListByAuthor_Call) Return(_a0 []models.Post, _a1 error) *MockPostRepository_ListByAuthor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepository_ListByAuthor_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]models.Post, error)) *MockPostRepository_ListByAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// ListFeed provides a mock function with given fields: ctx, viewerID, limit, offset
func (_m *MockPostRepository) ListFeed(ctx context.Context, viewerID string, limit int, offset int) ([]models.Post, error) {
	ret := _m.Called(ctx, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListFeed")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Post, error)); ok {
		return rf(ctx, viewerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Post); ok {
		r0 = rf(ctx, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepository_ListFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFeed'
type MockPostRepository_ListFeed_Call struct {
	*mock.Call
}

// ListFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID string
//   - limit int
//   - offset int
func (_e *MockPostRepository_Expecter) ListFeed(ctx interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockPostRepository_ListFeed_Call {
	return &MockPostRepository_ListFeed_Call{Call: _e.mock.On("ListFeed", ctx, viewerID, limit, offset)}
}

func (_c *MockPostRepository_ListFeed_Call) Run(run func(ctx context.Context, viewerID string, limit int, offset int)) *MockPostRepository_ListFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockPostRepository_ListFeed_Call) Return(_a0 []models.Post, _a1 error) *MockPostRepository_ListFeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepository_ListFeed_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.Post, error)) *MockPostRepository_ListFeed_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, authorID, content, visibility
func (_m *MockPostRepository) Update(ctx context.Context, id string, authorID string, content *string, visibility *string) (*models.Post, error) {
	ret := _m.Called(ctx, id, authorID, content, visibility)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, *string) (*models.Post, error)); ok {
		return rf(ctx, id, authorID, content, visibility)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, *string) *models.Post); ok {
		r0 = rf(ctx, id, authorID, content, visibility)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string, *string) error); ok {
		r1 = rf(ctx, id, authorID, content, visibility)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPostRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - authorID string
//   - content *string
//   - visibility *string
func (_e *MockPostRepository_Expecter) Update(ctx interface{}, id interface{}, authorID interface{}, content interface{}, visibility interface{}) *MockPostRepository_Update_Call {
	return &MockPostRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, authorID, content, visibility)}
}

func (_c *MockPostRepository_Update_Call) Run(run func(ctx context.Context, id string, authorID string, content *string, visibility *string)) *MockPostRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string), args[4].(*string))
	})
	return _c
}

func (_c *MockPostRepository_Update_Call) Return(_a0 *models.Post, _a1 error) *MockPostRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, *string, *string) (*models.Post, error)) *MockPostRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostRepository creates a new instance of MockPostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepository {
	mock := &MockPostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
