// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/donca/user-crud/internal/posts/models"
)

// MockPostService is an autogenerated mock type for the PostService type
type MockPostService struct {
	mock.Mock
}

type MockPostService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostService) EXPECT() *MockPostService_Expecter {
	return &MockPostService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, authorID, req
func (_m *MockPostService) Create(ctx context.Context, authorID string, req models.CreatePostRequest) (*models.Post, error) {
	ret := _m.Called(ctx, authorID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.CreatePostRequest) (*models.Post, error)); ok {
		return rf(ctx, authorID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.CreatePostRequest) *models.Post); ok {
		r0 = rf(ctx, authorID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.CreatePostRequest) error); ok {
		r1 = rf(ctx, authorID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - req models.CreatePostRequest
func (_e *MockPostService_Expecter) Create(ctx interface{}, authorID interface{}, req interface{}) *MockPostService_Create_Call {
	return &MockPostService_Create_Call{Call: _e.mock.On("Create", ctx, authorID, req)}
}

func (_c *MockPostService_Create_Call) Run(run func(ctx context.Context, authorID string, req models.CreatePostRequest)) *MockPostService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.CreatePostRequest))
	})
	return _c
}

func (_c *MockPostService_Create_Call) Return(_a0 *models.Post, _a1 error) *MockPostService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostService_Create_Call) RunAndReturn(run func(context.Context, string, models.CreatePostRequest) (*models.Post, error)) *MockPostService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, authorID, postID
func (_m *MockPostService) Delete(ctx context.Context, authorID string, postID string) error {
	ret := _m.Called(ctx, authorID, postID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, authorID, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPostService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - postID string
func (_e *MockPostService_Expecter) Delete(ctx interface{}, authorID interface{}, postID interface{}) *MockPostService_Delete_Call {
	return &MockPostService_Delete_Call{Call: _e.mock.On("Delete", ctx, authorID, postID)}
}

func (_c *MockPostService_Delete_Call) Run(run func(ctx context.Context, authorID string, postID string)) *MockPostService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPostService_Delete_Call) Return(_a0 error) *MockPostService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostService_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPostService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Feed provides a mock function with given fields: ctx, viewerID, limit, offset
func (_m *MockPostService) Feed(ctx context.Context, viewerID string, limit int, offset int) ([]models.Post, error) {
	ret := _m.Called(ctx, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Feed")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Post, error)); ok {
		return rf(ctx, viewerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Post); ok {
		r0 = rf(ctx, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostService_Feed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Feed'
type MockPostService_Feed_Call struct {
	*mock.Call
}

// Feed is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID string
//   - limit int
//   - offset int
func (_e *MockPostService_Expecter) Feed(ctx interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockPostService_Feed_Call {
	return &MockPostService_Feed_Call{Call: _e.mock.On("Feed", ctx, viewerID, limit, offset)}
}

func (_c *MockPostService_Feed_Call) Run(run func(ctx context.Context, viewerID string, limit int, offset int)) *MockPostService_Feed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockPostService_Feed_Call) Return(_a0 []models.Post, _a1 error) *MockPostService_Feed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostService_Feed_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.Post, error)) *MockPostService_Feed_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, postID, viewerID
func (_m *MockPostService) GetByID(ctx context.Context, postID string, viewerID string) (*models.Post, error) {
	ret := _m.Called(ctx, postID, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Post, error)); ok {
		return rf(ctx, postID, viewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Post); ok {
		r0 = rf(ctx, postID, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, postID, viewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPostService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - viewerID string
func (_e *MockPostService_Expecter) GetByID(ctx interface{}, postID interface{}, viewerID interface{}) *MockPostService_GetByID_Call {
	return &MockPostService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, postID, viewerID)}
}

func (_c *MockPostService_GetByID_Call) Run(run func(ctx context.Context, postID string, viewerID string)) *MockPostService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPostService_GetByID_Call) Return(_a0 *models.Post, _a1 error) *MockPostService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostService_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.Post, error)) *MockPostService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, authorID, viewerID, limit, offset
func (_m *MockPostService) ListByUser(ctx context.Context, authorID string, viewerID string, limit int, offset int) ([]models.Post, error) {
	ret := _m.Called(ctx, authorID, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]models.Post, error)); ok {
		return rf(ctx, authorID, viewerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []models.Post); ok {
		r0 = rf(ctx, authorID, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, authorID, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostService_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockPostService_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - viewerID string
//   - limit int
//   - offset int
func (_e *MockPostService_Expecter) ListByUser(ctx interface{}, authorID interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockPostService_ListByUser_Call {
	return &MockPostService_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, authorID, viewerID, limit, offset)}
}

func (_c *MockPostService_ListByUser_Call) Run(run func(ctx context.Context, authorID string, viewerID string, limit int, offset int)) *MockPostService_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockPostService_ListByUser_Call) Return(_a0 []models.Post, _a1 error) *MockPostService_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostService_ListByUser_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]models.Post, error)) *MockPostService_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, authorID, postID, req
func (_m *MockPostService) Update(ctx context.Context, authorID string, postID string, req models.UpdatePostRequest) (*models.Post, error) {
	ret := _m.Called(ctx, authorID, postID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, models.UpdatePostRequest) (*models.Post, error)); ok {
		return rf(ctx, authorID, postID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, models.UpdatePostRequest) *models.Post); ok {
		r0 = rf(ctx, authorID, postID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, models.UpdatePostRequest) error); ok {
		r1 = rf(ctx, authorID, postID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPostService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - postID string
//   - req models.UpdatePostRequest
func (_e *MockPostService_Expecter) Update(ctx interface{}, authorID interface{}, postID interface{}, req interface{}) *MockPostService_Update_Call {
	return &MockPostService_Update_Call{Call: _e.mock.On("Update", ctx, authorID, postID, req)}
}

func (_c *MockPostService_Update_Call) Run(run func(ctx context.Context, authorID string, postID string, req models.UpdatePostRequest)) *MockPostService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(models.UpdatePostRequest))
	})
	return _c
}

func (_c *MockPostService_Update_Call) Return(_a0 *models.Post, _a1 error) *MockPostService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostService_Update_Call) RunAndReturn(run func(context.Context, string, string, models.UpdatePostRequest) (*models.Post, error)) *MockPostService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostService creates a new instance of MockPostService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostService {
	mock := &MockPostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
