// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/donca/user-crud/internal/friendships/models"
)

// MockFriendshipRepository is an autogenerated mock type for the FriendshipRepository type
type MockFriendshipRepository struct {
	mock.Mock
}

type MockFriendshipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFriendshipRepository) EXPECT() *MockFriendshipRepository_Expecter {
	return &MockFriendshipRepository_Expecter{mock: &_m.Mock}
}

// AreFriends provides a mock function with given fields: ctx, userA, userB
func (_m *MockFriendshipRepository) AreFriends(ctx context.Context, userA string, userB string) (bool, error) {
	ret := _m.Called(ctx, userA, userB)

	if len(ret) == 0 {
		panic("no return value specified for AreFriends")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userA, userB)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userA, userB)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userA, userB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_AreFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AreFriends'
type MockFriendshipRepository_AreFriends_Call struct {
	*mock.Call
}

// AreFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - userA string
//   - userB string
func (_e *MockFriendshipRepository_Expecter) AreFriends(ctx interface{}, userA interface{}, userB interface{}) *MockFriendshipRepository_AreFriends_Call {
	return &MockFriendshipRepository_AreFriends_Call{Call: _e.mock.On("AreFriends", ctx, userA, userB)}
}

func (_c *MockFriendshipRepository_AreFriends_Call) Run(run func(ctx context.Context, userA string, userB string)) *MockFriendshipRepository_AreFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_AreFriends_Call) Return(_a0 bool, _a1 error) *MockFriendshipRepository_AreFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_AreFriends_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockFriendshipRepository_AreFriends_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRequest provides a mock function with given fields: ctx, requesterID, addresseeID
func (_m *MockFriendshipRepository) CreateRequest(ctx context.Context, requesterID string, addresseeID string) (*models.Friendship, error) {
	ret := _m.Called(ctx, requesterID, addresseeID)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Friendship, error)); ok {
		return rf(ctx, requesterID, addresseeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Friendship); ok {
		r0 = rf(ctx, requesterID, addresseeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, requesterID, addresseeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type MockFriendshipRepository_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID string
//   - addresseeID string
func (_e *MockFriendshipRepository_Expecter) CreateRequest(ctx interface{}, requesterID interface{}, addresseeID interface{}) *MockFriendshipRepository_CreateRequest_Call {
	return &MockFriendshipRepository_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, requesterID, addresseeID)}
}

func (_c *MockFriendshipRepository_CreateRequest_Call) Run(run func(ctx context.Context, requesterID string, addresseeID string)) *MockFriendshipRepository_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_CreateRequest_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipRepository_CreateRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_CreateRequest_Call) RunAndReturn(run func(context.Context, string, string) (*models.Friendship, error)) *MockFriendshipRepository_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// FindBetween provides a mock function with given fields: ctx, userA, userB
func (_m *MockFriendshipRepository) FindBetween(ctx context.Context, userA string, userB string) (*models.Friendship, error) {
	ret := _m.Called(ctx, userA, userB)

	if len(ret) == 0 {
		panic("no return value specified for FindBetween")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Friendship, error)); ok {
		return rf(ctx, userA, userB)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Friendship); ok {
		r0 = rf(ctx, userA, userB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userA, userB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_FindBetween_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBetween'
type MockFriendshipRepository_FindBetween_Call struct {
	*mock.Call
}

// FindBetween is a helper method to define mock.On call
//   - ctx context.Context
//   - userA string
//   - userB string
func (_e *MockFriendshipRepository_Expecter) FindBetween(ctx interface{}, userA interface{}, userB interface{}) *MockFriendshipRepository_FindBetween_Call {
	return &MockFriendshipRepository_FindBetween_Call{Call: _e.mock.On("FindBetween", ctx, userA, userB)}
}

func (_c *MockFriendshipRepository_FindBetween_Call) Run(run func(ctx context.Context, userA string, userB string)) *MockFriendshipRepository_FindBetween_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_FindBetween_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipRepository_FindBetween_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_FindBetween_Call) RunAndReturn(run func(context.Context, string, string) (*models.Friendship, error)) *MockFriendshipRepository_FindBetween_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockFriendshipRepository) FindByID(ctx context.Context, id string) (*models.Friendship, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Friendship, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Friendship); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockFriendshipRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFriendshipRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockFriendshipRepository_FindByID_Call {
	return &MockFriendshipRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockFriendshipRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockFriendshipRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_FindByID_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*models.Friendship, error)) *MockFriendshipRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListFriends provides a mock function with given fields: ctx, userID
func (_m *MockFriendshipRepository) ListFriends(ctx context.Context, userID string) ([]models.FriendProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListFriends")
	}

	var r0 []models.FriendProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.FriendProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.FriendProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FriendProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_ListFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFriends'
type MockFriendshipRepository_ListFriends_Call struct {
	*mock.Call
}

// ListFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipRepository_Expecter) ListFriends(ctx interface{}, userID interface{}) *MockFriendshipRepository_ListFriends_Call {
	return &MockFriendshipRepository_ListFriends_Call{Call: _e.mock.On("ListFriends", ctx, userID)}
}

func (_c *MockFriendshipRepository_ListFriends_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipRepository_ListFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_ListFriends_Call) Return(_a0 []models.FriendProfile, _a1 error) *MockFriendshipRepository_ListFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_ListFriends_Call) RunAndReturn(run func(context.Context, string) ([]models.FriendProfile, error)) *MockFriendshipRepository_ListFriends_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingReceived provides a mock function with given fields: ctx, userID
func (_m *MockFriendshipRepository) ListPendingReceived(ctx context.Context, userID string) ([]models.Friendship, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingReceived")
	}

	var r0 []models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Friendship, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Friendship); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_ListPendingReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingReceived'
type MockFriendshipRepository_ListPendingReceived_Call struct {
	*mock.Call
}

// ListPendingReceived is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipRepository_Expecter) ListPendingReceived(ctx interface{}, userID interface{}) *MockFriendshipRepository_ListPendingReceived_Call {
	return &MockFriendshipRepository_ListPendingReceived_Call{Call: _e.mock.On("ListPendingReceived", ctx, userID)}
}

func (_c *MockFriendshipRepository_ListPendingReceived_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipRepository_ListPendingReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_ListPendingReceived_Call) Return(_a0 []models.Friendship, _a1 error) *MockFriendshipRepository_ListPendingReceived_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_ListPendingReceived_Call) RunAndReturn(run func(context.Context, string) ([]models.Friendship, error)) *MockFriendshipRepository_ListPendingReceived_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingSent provides a mock function with given fields: ctx, userID
func (_m *MockFriendshipRepository) ListPendingSent(ctx context.Context, userID string) ([]models.Friendship, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingSent")
	}

	var r0 []models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Friendship, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Friendship); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_ListPendingSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingSent'
type MockFriendshipRepository_ListPendingSent_Call struct {
	*mock.Call
}

// ListPendingSent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipRepository_Expecter) ListPendingSent(ctx interface{}, userID interface{}) *MockFriendshipRepository_ListPendingSent_Call {
	return &MockFriendshipRepository_ListPendingSent_Call{Call: _e.mock.On("ListPendingSent", ctx, userID)}
}

func (_c *MockFriendshipRepository_ListPendingSent_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipRepository_ListPendingSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_ListPendingSent_Call) Return(_a0 []models.Friendship, _a1 error) *MockFriendshipRepository_ListPendingSent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_ListPendingSent_Call) RunAndReturn(run func(context.Context, string) ([]models.Friendship, error)) *MockFriendshipRepository_ListPendingSent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, addresseeID, status
func (_m *MockFriendshipRepository) UpdateStatus(ctx context.Context, id string, addresseeID string, status string) (*models.Friendship, error) {
	ret := _m.Called(ctx, id, addresseeID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.Friendship, error)); ok {
		return rf(ctx, id, addresseeID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.Friendship); ok {
		r0 = rf(ctx, id, addresseeID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, id, addresseeID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockFriendshipRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - addresseeID string
//   - status string
func (_e *MockFriendshipRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, addresseeID interface{}, status interface{}) *MockFriendshipRepository_UpdateStatus_Call {
	return &MockFriendshipRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, addresseeID, status)}
}

func (_c *MockFriendshipRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, addresseeID string, status string)) *MockFriendshipRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockFriendshipRepository_UpdateStatus_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipRepository_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.Friendship, error)) *MockFriendshipRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFriendshipRepository creates a new instance of MockFriendshipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFriendshipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFriendshipRepository {
	mock := &MockFriendshipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
