// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/donca/user-crud/internal/friendships/models"
)

// MockFriendshipService is an autogenerated mock type for the FriendshipService type
type MockFriendshipService struct {
	mock.Mock
}

type MockFriendshipService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFriendshipService) EXPECT() *MockFriendshipService_Expecter {
	return &MockFriendshipService_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function with given fields: ctx, userID, requestID
func (_m *MockFriendshipService) Accept(ctx context.Context, userID string, requestID string) (*models.Friendship, error) {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Friendship, error)); ok {
		return rf(ctx, userID, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Friendship); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipService_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockFriendshipService_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - requestID string
func (_e *MockFriendshipService_Expecter) Accept(ctx interface{}, userID interface{}, requestID interface{}) *MockFriendshipService_Accept_Call {
	return &MockFriendshipService_Accept_Call{Call: _e.mock.On("Accept", ctx, userID, requestID)}
}

func (_c *MockFriendshipService_Accept_Call) Run(run func(ctx context.Context, userID string, requestID string)) *MockFriendshipService_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFriendshipService_Accept_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipService_Accept_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipService_Accept_Call) RunAndReturn(run func(context.Context, string, string) (*models.Friendship, error)) *MockFriendshipService_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// ListFriends provides a mock function with given fields: ctx, userID
func (_m *MockFriendshipService) ListFriends(ctx context.Context, userID string) ([]models.FriendProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListFriends")
	}

	var r0 []models.FriendProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.FriendProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.FriendProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FriendProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipService_ListFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFriends'
type MockFriendshipService_ListFriends_Call struct {
	*mock.Call
}

// ListFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipService_Expecter) ListFriends(ctx interface{}, userID interface{}) *MockFriendshipService_ListFriends_Call {
	return &MockFriendshipService_ListFriends_Call{Call: _e.mock.On("ListFriends", ctx, userID)}
}

func (_c *MockFriendshipService_ListFriends_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipService_ListFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFriendshipService_ListFriends_Call) Return(_a0 []models.FriendProfile, _a1 error) *MockFriendshipService_ListFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipService_ListFriends_Call) RunAndReturn(run func(context.Context, string) ([]models.FriendProfile, error)) *MockFriendshipService_ListFriends_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingReceived provides a mock function with given fields: ctx, userID
func (_m *MockFriendshipService) ListPendingReceived(ctx context.Context, userID string) ([]models.Friendship, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingReceived")
	}

	var r0 []models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Friendship, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Friendship); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipService_ListPendingReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingReceived'
type MockFriendshipService_ListPendingReceived_Call struct {
	*mock.Call
}

// ListPendingReceived is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipService_Expecter) ListPendingReceived(ctx interface{}, userID interface{}) *MockFriendshipService_ListPendingReceived_Call {
	return &MockFriendshipService_ListPendingReceived_Call{Call: _e.mock.On("ListPendingReceived", ctx, userID)}
}

func (_c *MockFriendshipService_ListPendingReceived_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipService_ListPendingReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFriendshipService_ListPendingReceived_Call) Return(_a0 []models.Friendship, _a1 error) *MockFriendshipService_ListPendingReceived_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipService_ListPendingReceived_Call) RunAndReturn(run func(context.Context, string) ([]models.Friendship, error)) *MockFriendshipService_ListPendingReceived_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingSent provides a mock function with given fields: ctx, userID
func (_m *MockFriendshipService) ListPendingSent(ctx context.Context, userID string) ([]models.Friendship, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingSent")
	}

	var r0 []models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Friendship, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Friendship); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipService_ListPendingSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingSent'
type MockFriendshipService_ListPendingSent_Call struct {
	*mock.Call
}

// ListPendingSent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipService_Expecter) ListPendingSent(ctx interface{}, userID interface{}) *MockFriendshipService_ListPendingSent_Call {
	return &MockFriendshipService_ListPendingSent_Call{Call: _e.mock.On("ListPendingSent", ctx, userID)}
}

func (_c *MockFriendshipService_ListPendingSent_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipService_ListPendingSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFriendshipService_ListPendingSent_Call) Return(_a0 []models.Friendship, _a1 error) *MockFriendshipService_ListPendingSent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipService_ListPendingSent_Call) RunAndReturn(run func(context.Context, string) ([]models.Friendship, error)) *MockFriendshipService_ListPendingSent_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function with given fields: ctx, userID, requestID
func (_m *MockFriendshipService) Reject(ctx context.Context, userID string, requestID string) (*models.Friendship, error) {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Friendship, error)); ok {
		return rf(ctx, userID, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Friendship); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipService_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockFriendshipService_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - requestID string
func (_e *MockFriendshipService_Expecter) Reject(ctx interface{}, userID interface{}, requestID interface{}) *MockFriendshipService_Reject_Call {
	return &MockFriendshipService_Reject_Call{Call: _e.mock.On("Reject", ctx, userID, requestID)}
}

func (_c *MockFriendshipService_Reject_Call) Run(run func(ctx context.Context, userID string, requestID string)) *MockFriendshipService_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFriendshipService_Reject_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipService_Reject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipService_Reject_Call) RunAndReturn(run func(context.Context, string, string) (*models.Friendship, error)) *MockFriendshipService_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// SendRequest provides a mock function with given fields: ctx, requesterID, req
func (_m *MockFriendshipService) SendRequest(ctx context.Context, requesterID string, req models.FriendRequest) (*models.Friendship, error) {
	ret := _m.Called(ctx, requesterID, req)

	if len(ret) == 0 {
		panic("no return value specified for SendRequest")
	}

	var r0 *models.Friendship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.FriendRequest) (*models.Friendship, error)); ok {
		return rf(ctx, requesterID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.FriendRequest) *models.Friendship); ok {
		r0 = rf(ctx, requesterID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Friendship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.FriendRequest) error); ok {
		r1 = rf(ctx, requesterID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFriendshipService_SendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRequest'
type MockFriendshipService_SendRequest_Call struct {
	*mock.Call
}

// SendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID string
//   - req models.FriendRequest
func (_e *MockFriendshipService_Expecter) SendRequest(ctx interface{}, requesterID interface{}, req interface{}) *MockFriendshipService_SendRequest_Call {
	return &MockFriendshipService_SendRequest_Call{Call: _e.mock.On("SendRequest", ctx, requesterID, req)}
}

func (_c *MockFriendshipService_SendRequest_Call) Run(run func(ctx context.Context, requesterID string, req models.FriendRequest)) *MockFriendshipService_SendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.FriendRequest))
	})
	return _c
}

func (_c *MockFriendshipService_SendRequest_Call) Return(_a0 *models.Friendship, _a1 error) *MockFriendshipService_SendRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFriendshipService_SendRequest_Call) RunAndReturn(run func(context.Context, string, models.FriendRequest) (*models.Friendship, error)) *MockFriendshipService_SendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFriendshipService creates a new instance of MockFriendshipService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFriendshipService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFriendshipService {
	mock := &MockFriendshipService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
